### ISSUE TITLE
Backend - Trivias - Eliminar el botón agregar 

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#10]
Eliminemos el botón agregar trivias ya que no es necesario

![image](https://user-images.githubusercontent.com/38145241/40012753-076c2c38-5782-11e8-9caf-93b75fb3749a.png)

**Comment by oswaldopr** [comment]
Ocultar el botón es una actividad rápida y sencilla; sin embargo, cómo se cargarán las trivias reales en producción, una vez dé inicio el juego...¿?
Adicionalmente, el registro de las trivias se encuentra validado; es decir, no se podrán agregar más trivias si ya están asociadas todas las fases del mundial.

**Comment by sietepuentes** [comment]
Las trivias ya están pre-cargadas.  El usuario administrador no podrá agregar nuevas trivias, para evitar confusiones por favor ocultar el botón.

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
Gracias, listo.
