### ISSUE TITLE
Backend - Trivias - Editar

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#11]
Al editar una trivia, 
1) Ocultar estos campos
2) La fecha inicio y fin de la trivia no se debe actualizar en la base de datos.  Ya están fijas las fechas.
3) La fase tampoco se debe cambiar.

![image](https://user-images.githubusercontent.com/38145241/40012804-26656bae-5782-11e8-9c20-91c80bde25f9.png)

Con comentar esto se arregla en triviasProcesar.php, ya estaría ok pero si ocultamos en la pantalla mejor

/* $sql = "UPDATE trivias SET inicio = '$inicio', vencimiento = '$vencimiento', id_fase = $id_fase WHERE id_trivia = $id_trivia";
                $stmt = $DB->prepare($sql, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
                $stmt->execute(); */

**Comment by oswaldopr** [comment]
Los campos de inicio y vencimiento son de sólo lectura, están a nivel informativo. Una vez se registra una trivia éstos no cambian luego, sólo se muestran para informar al usuario estas fechas. De igual manera, como comentaba en el _issue_ #10, las trivias están validadas y nunca se podrán registrar trivias demás o intercambiar entre las fases.
Si aún sabiendo se quiere ocultar los campos, sólo indicarlo en un comentario posterior a este _issue_ y lo realizaré.

**Comment by sietepuentes** [comment]
Para el campo Fase, no ocultarlo, sino dejarlo deshabilitado para que no se pueda cambiar por el usuario.

Para el campo Fecha Inicio y fin, podemos dejarlo, pero no se tienen que poder actualizar en la base de datos.

**Comment by oswaldopr** [comment]
He aplicado una funcionalidad que no permita cambiar la selección del combo de las fases (a pesar que como ya comentaba está validado) para otorgar mayor tranquilidad. Pueden probar con todas las trivias y verán que ni la fase ni las fechas/horas se alteran. El inicio y vencimiento se toma desde los partidos, así que pueden tener tranquilidad también por allí.

**Comment by sietepuentes** [comment]
Oswaldo, no necesitamos que las trivias tomen la fecha de los partidos es por esto que te pedimos que no se altere la fecha que cada trivia tiene en la base de datos. 
Para que sepas, la trivia fase grupos debe comenzar ya mismo, en la base de datos le hemos puesto fecha inicio 14-mayo-2018.  Al actualizar las trivias, se modifica la fecha en la base de datos.

Necesitamos que NO se modifiquen las fechas que cada trivia tiene en la base de datos al editar la trivia.

No se si es claro el pedido pero como te comenté al comentar este código se arregla, podés dejar comentado ese bloque por favor?

/* $sql = "UPDATE trivias SET inicio = '$inicio', vencimiento = '$vencimiento', id_fase = $id_fase WHERE id_trivia = $id_trivia";
$stmt = $DB->prepare($sql, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
$stmt->execute(); */

**Comment by oswaldopr** [comment]
Hecho.

**Comment by carlos-segovia** [comment]
Funciona bien pero en la vista de edición se visualiza mal la fecha:
![image](https://user-images.githubusercontent.com/34341691/40313741-d20ca1a6-5cec-11e8-93a8-89a618d25d9b.png)

**Comment by oswaldopr** [comment]
Corregido.

**Comment by sietepuentes** [comment]
OK, en la pantalla de edición se visualizan las fechas correctas y al guardar no se modifican, cerrado.
![image](https://user-images.githubusercontent.com/38145241/40423392-cdf1a94a-5e68-11e8-9ea5-39cdd8f26b8f.png)
