### ISSUE TITLE
Backend - Trivias - Editar trivia campo portugues da error.

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#12]
Ingreso en el campo:
POR ¿Cuál e o temi es el actual campeón de la Copa Mundial de la FIFA?

![image](https://user-images.githubusercontent.com/38145241/40012914-8a0b110e-5782-11e8-9e55-e7661a793abd.png)

**Comment by oswaldopr** [comment]
Por favor probar habiendo limpiado la caché del navegador. De continuar el error, por favor dar mayores detalles para probar (número de la trivia, pregunta, etc.).

**Comment by carlos-segovia** [comment]
Oswaldo, prueba dejando un espacio después de POR asi:
![image](https://user-images.githubusercontent.com/34341691/40201775-6f2cfd40-59f6-11e8-98bf-3ac3268b0f1e.png)

lo probé recien y falla.

**Comment by sietepuentes** [comment]
Perfecto.
