### ISSUE TITLE
Frontend, cambiar texto en página de pronósticos.

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#17]
Cambiar los textos en la página de "Pronósticos"

Aquí les paso los textos que les debía para este punto: 1-Cambio del texto, mándanos en español y portugués de como deben quedar ambos.|| Mañana te paso ambos.

-Completá los resultados de los siguientes partidos. Tenés tiempo de hacerlo hasta 24 horas antes del comienzo de cada partido

-Complete com os resultados dos seguintes jogos. Você tem tempo até 24 horas antes do começo de cada jogo

**Comment by sietepuentes** [comment]
Listo en DEV, a probar.

**Comment by carlos-segovia** [comment]
Listo! probado en todas las fases en ES y PT. OK
