### ISSUE TITLE
Backend - Importar empleados - operación abortada

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#19]
Hola Oswaldo, 
Quise importar un listado de 20 empleados pero no pude, te dejo a continuación los errores y las correcciones que debemos hacer

1-Si existe algún error en el archivo, no abortemos todo el proceso, insertemos los correctos e informemos los incorrectos, pero no abortemos todo el proceso.  Puedes probar con el excel adjunto, los registros que funcionaron ok deben insertarse y no se están insertando.
2-Permitir que la contraseña tenga menos de 6 caracteres, con que tenga 1 es suficiente.
3-Campos departamento y ubicación, por favor permitir que si no son nulos tengan 1 caracter tambien (remover la validación de mínimo 2 caracteres).  No es necesario modificar la leyenda de la pantalla solo la validación del import.

[empleados_ejemplo (2).zip](https://github.com/sietepuentes/todosalacancha/files/2016737/empleados_ejemplo.2.zip)

![image](https://user-images.githubusercontent.com/38145241/40233560-e344088a-5a79-11e8-83bb-341375d1ef93.png)

**Comment by sietepuentes** [comment]
1-Si existe algún error en el archivo, no abortemos todo el proceso, insertemos los correctos e informemos los incorrectos, pero no abortemos todo el proceso. Puedes probar con el excel adjunto, los registros que funcionaron ok deben insertarse y no se están insertando.

ya este tema se había tocado con anterioridad y se acordó el proceso tal cual está... cuando se definió el requerimiento, Carlos me pidió que mostrara las líneas de errores o los valores incorrectos para que el administrador pudiera corregirlos y volver a importar el archivo; así lo programé... permitir insertar los registros válidos me llevaría a cambiar parte de la lógica, aunque suponiendo por un momento que lo hiciera, desde el punto de vista del administrador, sería más tedioso y laborioso el proceso de ese modo porque luego tendría que eliminar del archivo aquellos registros válidos para quedarse sólo con los inválidos y corregirlos! imaginen eso en un archivo con 6 mil registros...

pero bueno, si desean que se cambie lo puedo hacer pero no estaría cubierto dentro de lo pagado, justamente por lo que recién escribí, el proceso está como fue requerido y se debe cambiar gran parte del desarrollo!


** Se cierra ya que fue acordado dejar así la funcionalidad.

**Comment by oswaldopr** [comment]
Puntos 2 y 3, hecho.
