### ISSUE TITLE
Frontend - Puntos por trivias, goleador, y campeón

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#2]
Tenemos que ver como mostrar los puntos que obtuvo el usuario por trivia,s por goleador, y por campeón.
una idea puede ser algo así:

https://user-images.githubusercontent.com/35821871/39681255-6ca98c52-517f-11e8-9538-7f3562b09756.png
![image](https://user-images.githubusercontent.com/38145241/39932290-2089a1d2-5516-11e8-939d-1a0b1ea88b03.png)

En ranking.php agregué una columna para mostrar puntos por trivias por fase. Falta ver Campeón y Goleador.

**Comment by carlos-segovia** [comment]
esto se soluciona con el modal.
