### ISSUE TITLE
Backend - Importar empleados con email - log en pantalla

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#20]
1- Luego de importar el excel se muestra lo siguiente, por favor eliminar el log e informar por ejemplo cuántos emails se han enviado con la contraseña y a qué usuarios.  Y si el email fue enviado o si hubo algún error podemos mostrar?

2- El proceso es muy lento, se puede mejorar? importé 20 empleados en unos 20 segundos, y el cliente espera importar de a 6.000 por empresa.  

![image](https://user-images.githubusercontent.com/38145241/40233810-c2ebc496-5a7a-11e8-8c45-8407d26aa6d9.png)
![image](https://user-images.githubusercontent.com/38145241/40233842-e4b2e6c2-5a7a-11e8-95dc-b821a33dcf59.png)

**Comment by oswaldopr** [comment]
Se ha generado un archivo con la información del proceso de envío en el directorio `logs/`. Se muestra la cantidad de claves generadas si fuera el caso, de lo contrario, esta línea no se muestra para evitar confusiones. También, se muestra la cantidad de claves no enviadas y los respectivos destinatarios, nuevamente, sólo si aplica para evitar confusiones.
Sobre la lentitud del proceso, se debe exclusivamente a la demora de las conexiones por cada envío. Lo máximo en este caso que se pudo hacer es extender el tiempo de ejecución del script php para evitar sobrepasar el límite de tiempo de ejecución. Para informar al usuario, se muestra un mensaje con información de espera mientras el proceso se esté llevando a cabo.

**Comment by carlos-segovia** [comment]
Listo!OK
