### ISSUE TITLE
Frontend - Usuario con selección de perfil

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#21]
1. en la modal de bases y condiciones (al ingresar el usuario por primera vez) obligar a la selección de un país; si ya existe que se pueda cambiar y actualizar
2. en el ránking mostrar la bandera del país del usuario (Las banderas ya se encuentran en la carpeta img/equiposBanderas, probemos reusar estas, si no quedan bien buscamos otras.  Asimismo pueden faltar banderas ya que por ahora sólo tenemos las de los equipos que van al mundial, si falta alguna la agregamos).
3. en la sección del perfil permitir cambiar el país y actualizar

**Comment by oswaldopr** [comment]
Punto 1, hecho.

**Comment by oswaldopr** [comment]
Punto 2, hecho.

**Comment by oswaldopr** [comment]
Punto 3, hecho.
Adicionalmente, se cambia el idioma tanto en el _login_ como en la edición de perfil según el país elegido.

**Comment by sietepuentes** [comment]
Probado, funciona correctamente.
