### ISSUE TITLE
Backend - Importar empleados con email - log en pantalla - Contraseñas generadas

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/todosalacancha#22]
Cambiar el texto "Contraseñas generadas" por "Contraseñas Generadas random y enviadas por email : 3"
![image](https://user-images.githubusercontent.com/34341691/40312382-21d8c786-5ce9-11e8-81b8-7af5716dba18.png)

**Comment by sietepuentes** [comment]
En este caso para clarificar, modificar el texto de resultado:
"Contraseñas Generadas random y enviadas por email : 3"

Luego queda el issue que un usuario sin email, y sin contraseña, se está importando..

**Comment by oswaldopr** [comment]
Se han cambiado los textos como sigue:
**Contraseñas generadas aleatoriamente enviadas por correo-e: _999_**
y
**Contraseñas generadas aleatoriamente no enviadas por correo-e (error): _999_**

Esto no lo comprendí:
> Luego queda el issue que un usuario sin email, y sin contraseña, se está importando..

Si se refiere al por qué sucede, un empleado sin correo-e y sin contraseña se importa porque con anterioridad se solicitó eliminar la validación del correo electrónico y más recientemente (con la generación de claves aleatorias) se pidió también eliminar la validación de las contraseñas.

**Comment by sietepuentes** [comment]
Ok.  
![image](https://user-images.githubusercontent.com/38145241/40511981-cb443a22-5f77-11e8-9faf-0978b41e4447.png)
