### ISSUE TITLE
Backend - Mail de bienvenida

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/todosalacancha#23]
en el mail dice:
![image](https://user-images.githubusercontent.com/34341691/40312674-e1ec4232-5ce9-11e8-9d26-c252fb1a917e.png)
la url a la que apunta esta bien pero si alguien copia y pega el texto no le va a funcionar.
cambiar el texto por la URL asi: https://www.todosalacancha.com/empresa

**Comment by oswaldopr** [comment]
Hecho.

**Comment by carlos-segovia** [comment]
Listo! OK
