### ISSUE TITLE
Frontend - Pronosticos - Posicion ranking va cambiando

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#24]
empresa google, usuario rmurer pass rmurer

Al cambiar las fases en pronósticos view, se va cambiando la posición del ránking.  Dejemos la posición fija. 

![image](https://user-images.githubusercontent.com/38145241/40315204-17985860-5cf1-11e8-9b7e-c26523dbd606.png)

![image](https://user-images.githubusercontent.com/38145241/40315244-38e5627e-5cf1-11e8-9f7e-146fbb3a0b79.png)

![image](https://user-images.githubusercontent.com/38145241/40315273-49fa78a6-5cf1-11e8-979c-f9ccb953a1ef.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
Perfecto, probado, ya no cambia.
