### ISSUE TITLE
Frontend - Ranking - Banderas no se visualizan en solapas, quitar circulo verde

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#25]
https://todosalacancha.sietepuentes.com/google/
usuario rmurer, pass rmurer

Issues
1-Si el usuario no tiene país asociado, no mostrar ningún circulito verde ni bandera.
2-Al clickear en las solapas "Ranking General", "Octavos" etc, se debe respetar la misma funcionalidad dinámica de banderas.  

Ver screenshots:

![image](https://user-images.githubusercontent.com/38145241/40316039-67a8f56a-5cf3-11e8-9f89-279ffd315568.png)

![image](https://user-images.githubusercontent.com/38145241/40316084-89f258b4-5cf3-11e8-95c4-44f584a431ec.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
Un issue más Oswaldo, verificar la versión mobile por favor.

**Comment by oswaldopr** [comment]
Corregido también para versión móvil.

**Comment by sietepuentes** [comment]
Perfecto. Cerrado.
![image](https://user-images.githubusercontent.com/38145241/40423972-7d6467e0-5e6a-11e8-8c10-897709f1d522.png)
