### ISSUE TITLE
Frontend - Cambiar las banderas por texto

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#26]
En vez de mostrar banderitas, mostrar "ES" | "PT" para selección de idiomas.

**Comment by sietepuentes** [comment]
Falta en el login
![image](https://user-images.githubusercontent.com/38145241/40452044-e797270a-5eb6-11e8-995e-0f7907503be8.png)

**Comment by carlos-segovia** [comment]
LIsto! :)
