### ISSUE TITLE
 Backend - Redimensionar imagenes de perfil

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/todosalacancha#27]
Cuando se suba la imagen de perfil tanto desde el front como desde el backoffice, redimensionarla proporcionalmente con un maximo de 200 px de ancho para que pese lo menos posible.

**Comment by oswaldopr** [comment]
Aún no implemento la solución a esto pero, por qué no darle uso a las configuraciones/validaciones que se pidieron con anterioridad y se restringe el tamaño de las imágenes de perfil a 200px de ancho como máximo, a través de la configuración de los parámetros para imágenes. También existe un parámetro para el tamaño (peso) del archivo.

**Comment by sietepuentes** [comment]
Oswaldo, no podemos limitar tanto al usuario (que en general va a subir imágenes desde su mobile sacándose una foto).  No podrá hacer una redimensión previa el usuario, es por esto, que debemos permitir al usuario subir cualquier imagen, pero "on the fly" cuando se hace el upload, achicarla nosotros.

**Comment by oswaldopr** [comment]
Hecho.

**Comment by robert-dm** [comment]
Funciona muy bien.
