### ISSUE TITLE
Agregar logo Todos para a copa en portugues y la lógica

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#28]

**Comment by sietepuentes** [comment]
Listo, hecho, probar.

**Comment by carlos-segovia** [comment]
Perfecto! 10 pts

**Comment by carlos-segovia** [comment]
En el login no esta funcionando

**Comment by sietepuentes** [comment]
listo
![image](https://user-images.githubusercontent.com/38145241/40512742-20c33212-5f7a-11e8-96bc-1cbd176ae0a1.png)
