### ISSUE TITLE
Frontend - Login con modal - Selección de país

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#30]
1- en ABM creé un empleado (empresa despegar, usuario rmurer rmurer), y lo asigné al país Brasil en el momento que fue creado
2- el usuario hace el primer login, y le aparece el modal para aceptar bases
3- en el modal se muestra la selección de países (pero no aparece seleccionado el país Brasil)
4- el usuario está obligado a elegir país, pero debe venir pre-seleccionado el país que asignó el administrador al momento de crear el usuario

** si el empleado ya tiene un país no debe estar obligado a elegir otro, sino que es opcional el cambio **

![image](https://user-images.githubusercontent.com/38145241/40431846-a4b20280-5e7e-11e8-95f1-1abcc5181e73.png)

**Comment by oswaldopr** [comment]
Arreglado. Se había perdido la funcionalidad de la pre-selección del país.

**Comment by sietepuentes** [comment]
Está ok el select, ahora, pero... si el usuario está asignado a Brasil, el modal se debe mostrar en portugues

usuario rmurer/rmurer, asignado a país Brasil, ve el modal de bases en español 

![image](https://user-images.githubusercontent.com/38145241/40451744-01f8edc8-5eb6-11e8-9691-fae48507c56d.png)

**Comment by carlos-segovia** [comment]
Funciona. También probé de cambiar el país preseleccionado y anduvo bien.
