### ISSUE TITLE
Frontend - Ranking - Posición mal informada

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#33]
empresa google, usuario rmurer8 rmurer8, se muestra en posición #2, pero se informa en posición #1 en la parte izquierda 

![image](https://user-images.githubusercontent.com/38145241/40551490-764c9d9c-6013-11e8-9750-c86171f6cec9.png)

**Comment by oswaldopr** [comment]
Corregido.

**Comment by robert-dm** [comment]
Perfecto
