### ISSUE TITLE
Frontend - Modal Ranking - Textos dinámicos

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#34]
Los textos siguientes tienen que ser dinámicos dependiendo del lenguaje

En español:
-Posición Ranking
-Total Puntos
-Puntos por pronósticos
-Puntos por trivias:
-Puntos extra:

En portugués:
-Posição do ranking
-Pontos
-Pontos palpites
-Pontos testes
-Pontos ganhador / goleador: 

![image](https://user-images.githubusercontent.com/38145241/40551826-63503f86-6014-11e8-8d88-7f074a6335ad.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
Prefecto!
![image](https://user-images.githubusercontent.com/38145241/40556708-141f0d2e-6024-11e8-8395-200f747ff7af.png)

![image](https://user-images.githubusercontent.com/38145241/40556715-1f40feec-6024-11e8-8667-dabf0f637445.png)
