### ISSUE TITLE
Frontend Mobile - Icono de perfil cortado

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/todosalacancha#36]
![image](https://user-images.githubusercontent.com/34341691/40588298-c8812cb4-61b1-11e8-9e50-f423c839bfb0.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
OK

![image](https://user-images.githubusercontent.com/38145241/40751328-164bf578-6441-11e8-8516-edae4edd83f4.png)
