### ISSUE TITLE
Frontend - Perfil - Error en Edicion de perfil

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/todosalacancha#37]
Si hacemos click en Editar perfil sin modificar nada o para cambiar contraseña sale el error de abajo.
Si cambiamos la contraseña, sale el error pero la contraseña si se cambia.

A PHP Error was encountered

Severity: Warning

Message: file_get_contents(): Filename cannot be empty

Filename: controllers/Index.php

Line Number: 533

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 533
Function: file_get_contents

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: imagecreatefromstring(): Empty string or invalid image

Filename: controllers/Index.php

Line Number: 533

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 533
Function: imagecreatefromstring

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: exif_read_data(): Filename cannot be empty

Filename: controllers/Index.php

Line Number: 536

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 536
Function: exif_read_data

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: exif_read_data(): Unable to open file

Filename: controllers/Index.php

Line Number: 536

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 536
Function: exif_read_data

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: getimagesize(): Filename cannot be empty

Filename: controllers/Index.php

Line Number: 582

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 582
Function: getimagesize

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: imagejpeg() expects parameter 1 to be resource, boolean given

Filename: controllers/Index.php

Line Number: 589

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 589
Function: imagejpeg

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: imagedestroy() expects parameter 1 to be resource, boolean given

Filename: controllers/Index.php

Line Number: 590

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 590
Function: imagedestroy

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/ftp-user/html/todosalacancha/system/core/Exceptions.php:271)

Filename: helpers/url_helper.php

Line Number: 564

Backtrace:

File: /home/ftp-user/html/todosalacancha/application/controllers/Index.php
Line: 638
Function: redirect

File: /home/ftp-user/html/todosalacancha/index.php
Line: 317
Function: require_once

**Comment by oswaldopr** [comment]
Corregido.

**Comment by sietepuentes** [comment]
En versión Mobile, clickeo en Actualizar perfil, se muestra que el perfil fue actualizado, no da error, está ok.

En versión Web, clickeo en Actualizar perfil, sin cambiar nada, no da error ni muestra mensaje, no hace nada.

**Comment by robert-dm** [comment]
Perfecto, web y mobile probado, portugues y español. ok.
