### ISSUE TITLE
Pronosticos Mobile - UX Error

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/todosalacancha#39]
![image](https://user-images.githubusercontent.com/34341691/40588701-f0044ae0-61b7-11e8-932d-278951775b6e.png)
Cuando terminan los partidos desaparece el botón Pronosticar. Continua con elegir Campeon y Goleador y al final hay un botón Enviar Respuesta. 
Se entiende que haciendo click en Enviar Respuesta se guarda todo y NO es así.

**Comment by sietepuentes** [comment]
En versión mobile en portugues, al clickear en el botón Enviar Respuesta, aparece doble el modal (primero en español, y luego en portugues)

**Comment by robert-dm** [comment]
Lo probé y funciona perfecto.  Lo dejo abierto por si @carlos-segovia quiere probar algo más.

**Comment by robert-dm** [comment]
Perfecto
