### ISSUE TITLE
Frontend - Ranking wrong calculated

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#4]
[ec2-user@ip-172-31-20-8 7puentes]$ date
Wed Jun 27 15:49:17 UTC 2018

user rmurer10
pass rmurer10

company 7puentes

rmurer10 have 140 points for predictions in grupos phase and 140 more for trivias total 280
carlos have only 140 points for predictions.

See below image, rmurer10 is in position 2 but this is wrong, he is in first position.

![image](https://user-images.githubusercontent.com/38145241/39932405-6b45c85e-5516-11e8-9bec-969d411fdd4e.png)

![image](https://user-images.githubusercontent.com/38145241/39932411-6de8d5a6-5516-11e8-904a-46e4ef18427a.png)

**Comment by oswaldopr** [comment]
El empleado **rmurer10** en la empresa **7puentes** no posee puntos por trivias, lo he verificado directamente en la base de datos (tabla `puntos_empleados`).
El cálculo para listar el ránking sí considera los puntos por trivias, ver empleado **rmurer8** en la empresa **google**; posee 140 puntos por trivias y manualmente he agregado 20 puntos por el pronóstico del primer partido. En el listado se muestra correctamente la posición (13) con 160 puntos.

**Comment by sietepuentes** [comment]
Gracias Oswaldo.  Cuando creamos el issue hace 12 días, el usuario rmurer sí tenía puntos pero bueno luego hemos modificado la base.

Sobre tu último comentario "El ránking por fases (tabla del lado izquierdo Tu Ránking) sí presentaba fallas ya que allí no se consideraba la relación con las trivias. Se ha corregido." esto estaba funcionando mal solamente la columna "puesto" como se ve en la imagen de cuando se creó el issue, pero la columna "Puntos pronósticos" estaba bien, ya que solo debe mostrar los puntos por los partidos (y no los de las trivias).  Los puntos de las trivias se muestran en la tercer columna "Puntos Trivia" para la fase.

Por favor revisa la imagen que sigue para que te quede claro, en la columna Puntos Pronósticos debería decir 20 para la fase de grupos.

![image](https://user-images.githubusercontent.com/38145241/40423796-ff19f526-5e69-11e8-90a6-c7eeb81cab72.png)

**Comment by carlos-segovia** [comment]
Listo!
