### ISSUE TITLE
Frontend - Pronosticar partidos error validacion de horas

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/todosalacancha#41]
Server date [ec2-user@ip-172-31-20-8 html]$  sudo date --set "30 Jun 2018 15:00:00"
Sat Jun 30 15:00:00 -03 2018

Empresa google, usuario rmurer/rmurer

El usuario va a pronosticar la fase de octavos, y puede pronosticar los partidos aunque falten menos de 24hs segun indica la pantalla:

![image](https://user-images.githubusercontent.com/35821871/40590973-0fe616b4-61df-11e8-95b9-d38c6632b027.png)

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
Funciona perfecto, probado en web y mobile
![image](https://user-images.githubusercontent.com/38145241/40751735-d882e826-6442-11e8-9a0f-4d1ef9708115.png)

![image](https://user-images.githubusercontent.com/38145241/40751749-e484386e-6442-11e8-96f8-18858f1a58d6.png)
