### ISSUE TITLE
Frontend - Selección de país obligatoria - está bien? para todas las empresas?

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/todosalacancha#42]
El select de países entiendo que debe ser obligatorio sólo si la empresa tiene idioma adicional portugues, lo podemos dejar así, pero es muy probable que pidan el cambio (ya que era sólo para despegar este pedido)

![image](https://user-images.githubusercontent.com/35821871/40591437-b082fd64-61e7-11e8-9820-020ddb920027.png)

**Comment by carlos-segovia** [comment]
Esperamos.
