### ISSUE TITLE
Ranking - Show modal with user data

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/todosalacancha#5]
El modal está listo, hay que cargar sólo el modal del usuario que se hizo click para no cargar todos los usuarios.

![image](https://user-images.githubusercontent.com/38145241/39939285-336a22e8-552c-11e8-8cd9-61a9fddcbaf7.png)

**Comment by sietepuentes** [comment]
Listo en DEV, falta hacer el cálculo de puntos.

**Comment by oswaldopr** [comment]
Hecho.

**Comment by sietepuentes** [comment]
Oswaldo, podrás mostrar el modal también en las solapas de diferentes fases del mundial?

**Comment by carlos-segovia** [comment]
En ranking general esta el link para abrir el modal pero si cambio de fase y vuelvo a ranking general se pierde el link y logicamente no se puede abrir el modal.

**Comment by carlos-segovia** [comment]
Listo!
